# Generated by Django 4.2.11 on 2024-08-06 20:59

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import pulpcore.app.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0121_add_profile_artifacts_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastUpdatedRecord',
            fields=[
                ('pulp_id', models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('content_last_updated', models.DateTimeField(null=True)),
                ('last_replication', models.DateTimeField()),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.distribution')),
                ('upstream_pulp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.upstreampulp')),
            ],
            options={
                'unique_together': {('distribution', 'upstream_pulp')},
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='upstreampulp',
            name='last_updated_timestamps',
            field=models.ManyToManyField(through='core.LastUpdatedRecord', to='core.distribution'),
        ),
    ]
